spring.application.name=campusjobboard
spring.datasource.url=jdbc:mysql://localhost:3306/campusjobboard_db
spring.datasource.username=root
spring.datasource.password=Femi-2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
server.port=8080
