spring.application.name=campusjobboard
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/campusjobboard_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
server.port=${PORT:8080}

logging.file.path=${LOG_PATH:logs}
logging.level.com.example.campusjobboard=INFO

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
